DEFAULT_PORT = 9000

# Operation modes
MODE_SERVER = 0
MODE_CLIENT = 1

# Protocol commands
COMMAND_PREFIX     = "/"
COMMAND_SEPARATOR  = ":"
COMMAND_HELO       = COMMAND_PREFIX + "HELO"
COMMAND_REDY       = COMMAND_PREFIX + "REDY"
COMMAND_PUBLIC_KEY = COMMAND_PREFIX + "PUB_KEY"
COMMAND_AES_KEY    = COMMAND_PREFIX + "AES_KEY"
COMMAND_AES_IV     = COMMAND_PREFIX + "AES_IV"
COMMAND_AES_SALT   = COMMAND_PREFIX + "AES_SALT"
COMMAND_MSG        = COMMAND_PREFIX + "MSG"
COMMAND_END        = COMMAND_PREFIX + "END"
COMMAND_ERR        = COMMAND_PREFIX + "ERR"

COMMANDS = [COMMAND_HELO, COMMAND_REDY, COMMAND_PUBLIC_KEY, COMMAND_AES_KEY, COMMAND_AES_IV,
            COMMAND_AES_SALT, COMMAND_MSG, COMMAND_END, COMMAND_ERR]

# Message sources
SENDER   = 0
RECEIVER = 1
SERVICE  = 2

# QT UI custom button codes
BUTTON_OKAY   = 0
BUTTON_CANCEL = 1
BUTTON_FORGOT = 2
