TITLE_NETWORK_ERROR  = "Network Error"
TITLE_CRYPTO_ERROR   = "Crypto Error"
TITLE_END_CONNECTION = "Connection Ended"

UNEXPECTED_CLOSE_CONNECTION = "Remote unexpectedly closed connection"
UNEXPECTED_DATA             = "Remote sent unexpected data"
UNEXPECTED_COMMAND          = "Receieved unexpected command"
NO_COMMAND_SEPARATOR        = "Command separator not found in message"
UNKNOWN_ENCRYPTION_TYPE     = "Unknown encryption type"
VERIFY_PASSPHRASE_FAILED    = "Passphrases do not match"
BAD_PASSPHRASE              = "Wrong passphrase"
BAD_PASSPHRASE_VERBOSE      = "An incorrect passphrase was entered"
FAILED_TO_START_SERVER      = "Error starting server"
FAILED_TO_ACCEPT_CLIENT     = "Error accepting client connection"
FAILED_TO_CONNECT           = "Error connecting to server"
CLIENT_ENDED_CONNECTION     = "The client requested to end the connection"